# Generated by Django 5.1.6 on 2025-03-23 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ordermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finaltotal', models.FloatField()),
                ('phone', models.BigIntegerField()),
                ('address', models.TextField()),
                ('paymode', models.CharField(max_length=40)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.registermodel')),
            ],
        ),
    ]
