# Generated by Django 5.1.4 on 2025-03-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_ordermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='orderid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='orderstatus',
            field=models.IntegerField(default=1),
        ),
    ]
