# Generated by Django 5.1.4 on 2025-03-27 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_cart_orderid_alter_cart_orderstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcatname', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='catid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.subcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcatid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.subcategory'),
        ),
    ]
