# Generated by Django 5.1.4 on 2025-03-27 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_subcategory_category_catid_product_subcatid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='catid',
            new_name='subcatid',
        ),
    ]
