# Generated by Django 5.1.4 on 2025-03-27 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_catid_category_subcatid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcatid',
        ),
    ]
